name: Release Changelog
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  release-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - uses: release-changelog-builder/release-changelog-builder@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: CHANGELOG.md
